Project01/LICENSE
Project01/index.html
Project01/readme.md
Project01/script.js
Project01/style.css

his Project is all about the conversion of speech to text.
#5
Tech Stack: HTML, CSS, Javascript
Go to Project01 branch .
Then, visit readme.md where you will find complete information about the project.
This project is good to go for the beginners.
If you liked my project then assign me the PR under SWOC'25.

Added project01

---

Project02/index.html
Project02/script.js
Project02/style.css

This pull request adds an improved version of the Snake Game with some cool new features. The game now includes:
1-Arrow Key or On-Screen Controls: Players can move the snake using the arrow keys or buttons on the screen.
2-Score and High Score: The game tracks your current score and stores the highest score in your browser.
3-Obstacles and Power-ups: As you level up, new obstacles appear, and power-ups can make the game easier for a short time.
4-Bonus Food: Eating special bonus food gives extra points.
5-Mobile and Desktop Friendly: The game looks great and works well on both computers and phones.
This version makes the game more fun and challenging while keeping it easy to play. The code is also optimized for smooth performance.

project 2 (snake game)

---

stone_paper_scissors/first.js
stone_paper_scissors/index.html
stone_paper_scissors/style.css

Developed an interactive Stone Paper Scissors game using JavaScript, featuring dynamic score tracking and user interface updates.
- Initialized user and computer scores.
- Implemented computer choice generation with random selection.
- Added event listeners for user choices and reset functionality.
- Developed game logic to determine outcomes (win, lose, draw).
- Updated DOM elements to reflect current scores and game messages.
- Verified correct score incrementation for wins and losses.
- Ensured accurate game outcome messages for all possible scenarios.
- Tested reset functionality to confirm proper score and message clearing.

Implement Stone Paper Scissors Game with Score Tracking

---

Project05/index.html
Project05/todolist.css
Project05/todolist.js

#8 
1. Create a webpage to manage your daily tasks.
2.  You can also save, download, watch your tasks.
- Go to Project05
- then move into index.html and click on live server at bottom-right.
- you can check the webpage and reccoment changes on it.

Project 05

---

Project7 -CountDown Timer/index.html
Project7 -CountDown Timer/script.js
Project7 -CountDown Timer/style.css

#18 Countdown Timer fixed , Add SWOC labels , Intermediate level to this pr @SOMNATH0904                                                                 Screenshots :
https://github.com/user-attachments/assets/0ac9769c-d9f2-4eb6-95a4-810a223b5ecc

Project7 Fixed Countdown Timer 

---

Project9 - Simple Calculator/index.html
Project9 - Simple Calculator/script.js
Project9 - Simple Calculator/styles.css

Project 9 - Simple Calculator is added to the DevSphere @SOMNATH0904 Add SWOC labels and Advance level to this PR .
Screenrecording :
https://github.com/user-attachments/assets/e0757f88-4304-4273-b49f-2fccf334fd59

Project 9 : Simple Calculator Fixed

---

.vscode/settings.json
Project - TowerGame/index.html
Project - TowerGame/script.js
Project - TowerGame/style.css

Add tower game

---

projects/Memory-Game/README.md
projects/Memory-Game/index.html
projects/Memory-Game/script.js
projects/Memory-Game/styles.css
projects/Quiz-App-Timer/README.md
projects/Quiz-App-Timer/index.html
projects/Quiz-App-Timer/script.js
projects/Quiz-App-Timer/style.css

An interactive quiz application with multiple categories, difficulty levels, and a timer feature.
- Multiple quiz categories:
- General Knowledge
- Science
- History
- Technology
- Three difficulty levels:
- Easy (60 seconds)
- Medium (45 seconds)
- Hard (30 seconds)
- Customizable quiz length (5, 10, 15, or 20 questions)
- Timer countdown for each quiz
- Beautiful UI with category icons
- Detailed results with explanations
- Score tracking and performance statistics #43

Add quiz app #43

---

projects/Digital-Clock/README.md
projects/Digital-Clock/index.html
projects/Digital-Clock/script.js
projects/Digital-Clock/style.css
projects/Memory-Game/README.md
projects/Memory-Game/index.html
projects/Memory-Game/script.js
projects/Memory-Game/styles.css
projects/Quiz-App-Timer/README.md
projects/Quiz-App-Timer/index.html
projects/Quiz-App-Timer/script.js
projects/Quiz-App-Timer/style.css

A modern and feature-rich digital clock built with HTML, CSS, and JavaScript.
- Real-time clock display with seconds
- Multiple timezone support
- Toggle between 12/24-hour format
- Dark/Light theme toggle
- Responsive design
- Beautiful glass-morphism UI
- Animated heart beat effect
- HTML5
- CSS3 (with CSS Variables)
- JavaScript (ES6+)
- Font Awesome Icons
The project is located in the `projects/Digital-Clock` directory and includes:
- index.html
- style.css
- script.js
- README.md

Add Digital Clock Project with Modern UI and Multiple Features

---

Project05/todolist.css
Project12/index.html
Project12/script.js
Project12/style.css

#17 
It is a game of 2 players:
- One has to choose 'X' and another player ahs to choose 'O'
- They have to play in a square divided into 9 pieces .
- If one of the player make a line (straight, diagonal) .
- He wins
Tech Stack : HTML, CSS, Javascript

Tic Tac Toe

---

Project 13 - Guess the random Number Game/index.html
Project 13 - Guess the random Number Game/script.js
Project 13 - Guess the random Number Game/styles.css

#37 Issue Solved Guess the RandomNumber Added to the Project , Add SWOC Labels to this Issue , Add Intermediate to this PR , @SOMNATH0904 
Screenshots :
https://github.com/user-attachments/assets/2bd751c8-1a6e-4fcd-bd68-bf612134f8bf

Project 13 - Guess random Number

---

Project13 - Word Scrambler/index.html
Project13 - Word Scrambler/script.js
Project13 - Word Scrambler/style.css
Project13 - Word Scrambler/words.js

This is a Word scrambling game. The words will be jumbled, and you have to guess the correct word. There will be a timer of 30s. Guessing the word within the time limit will win you the game
Happy to participate in SWOC 😊

Add Word Scrambler to DevSphere

---

Project19/index.html
Project19/script.js
Project19/style.css

#50 
A beginner-level project for web developers to learn about cursor animation.
Tech stack: HTML, CSS, Vanilla Javascript

Animated Cursor 

---

HSL Color Generator/index.html
HSL Color Generator/script.js
HSL Color Generator/style.css

#73 
- HSL -> index.html, style.css, script.js
- check by running on the live server
It is a very beginner-level project to learn color theory and bthe asics of web development

HSL Color Generator

---

Project 28 - Memory Matching Game/index.html
Project 28 - Memory Matching Game/script.js
Project 28 - Memory Matching Game/styles.css

Fixed  Project 28 - memory Matching Game , Add SWOC, Intermediate Labels to this Issue @SOMNATH0904 
Screenrecording :
Uploading Screen Recording 2025-01-09 175633.mp4…

Project 28 - Memory Matching Game

---

MOVIE APP/index.html
MOVIE APP/script.js
MOVIE APP/style.css

A modern web application for browsing and searching movies using the TMDB API.
- Modern and responsive UI design
- Movie search functionality
- Display of movie posters, ratings, and release years
- Grid layout for better movie browsing experience
1. Get an API key from [TMDB](https://www.themoviedb.org/documentation/api)
2. Replace `give_your_api_key` in [script.js](cci:7://file:///c:/Users/PRATYUSH/Desktop/SWOC/DevSphere/MOVIE%20APP/script.js:0:0-0:0) with your TMDB API key
3. Open `index.html` in a web browser
- Built with vanilla JavaScript
- Uses modern CSS Grid and Flexbox
- Implements async/await for API calls
- Responsive design for all screen sizes

 Movie App with TMDB Integration

---

typewriter/typewriter.css
typewriter/typewriter.html
typewriter/typewriter.js

Experience the charm of a retro typewriter brought to life with modern web technologies. This interactive website dynamically types out phrases with customizable options for text input, speed adjustment, and theme toggling. Built with HTML, CSS, and JavaScript, it offers a seamless user experience with features like adding your own text, changing backgrounds, and a responsive design for all devices. Dive into this engaging project that blends nostalgia with creativity!

Dynamic Typewriter Showcase

---

Project4 - StonePaperScissor/style.css

responsiveness of stone paper scissor is ready issue #36

---

Project3 - SnakeGame/index.html
Project3 - SnakeGame/script.js
Project3 - SnakeGame/style.css
Project4 - StonePaperScissor/style.css

Issue #34 : snake game's game over model is ready

---

Gesture_Controlled_Pingpong/README.md
Gesture_Controlled_Pingpong/pingpong.py
Gesture_Controlled_Pingpong/requirements.txt

1. Made using pygame, openCV, mediapipe
2. Bars on screen are controlled using hand gestures.
3. Detects Hand Motion

Gesture_Controlled_Pingpong

---

Project35-AdminDashboard/dashboard/dashboard.css
Project35-AdminDashboard/dashboard/dashboard.html
Project35-AdminDashboard/index.html
Project35-AdminDashboard/script.js
Project35-AdminDashboard/style.css

adding Project35

---

periodic Table/index.html
periodic Table/script.js
periodic Table/styles.css

This pull request introduces a fully functional and interactive periodic table of elements hosted on a website. The website provides users with easy access to detailed information about each element, including its atomic number, symbol, name, atomic mass, group, and period. The interface is designed to be user-friendly, allowing users to click on any element to view its detailed properties. This feature aims to enhance learning and provide a valuable resource for students, teachers, and chemistry enthusiasts. The periodic table is fully responsive, ensuring compatibility across different devices.

Add Periodic Table Website with Interactive Features

---

Project31 - PlantWebsite/plant.css
Project31 - PlantWebsite/plant.html

Fixes: #95 
https://github.com/user-attachments/assets/9ffb86ef-4a14-485b-86e8-da239410aff2
@SOMNATH0904 Please review

Add toggle button

---

Project38 - TextToSpeechConverter/README.md
Project38 - TextToSpeechConverter/index.html
Project38 - TextToSpeechConverter/script.js
Project38 - TextToSpeechConverter/style.css

FIXES #78 
@SOMNATH0904 
created Text To Speech Converter

TextToSpeechConverter FIXES #78

---

Project04 - StonePaperScissor/style.css
Project31 - PlantWebsite/plant.css
Project31 - PlantWebsite/plant.html

https://github.com/user-attachments/assets/a23af59b-0ae0-41a5-8cfe-b9e329ac58a8
Fixes: #96

make Responsiveness 

---

Project38-PocketImage/index.html
Project38-PocketImage/script.js
Project38-PocketImage/style.css
Project39-QRCodeGenerator/index.html
Project39-QRCodeGenerator/script.js
Project39-QRCodeGenerator/style.css
Project40-FlashiThings/index.html
Project40-FlashiThings/script.js
Project40-FlashiThings/style.css

Adding project38

---

Project38-PocketImage/index.html
Project38-PocketImage/script.js
Project38-PocketImage/style.css
Project39-QRCodeGenerator/index.html
Project39-QRCodeGenerator/script.js
Project39-QRCodeGenerator/style.css

Adding QR generator

---

Project38-PocketImage/index.html
Project38-PocketImage/script.js
Project38-PocketImage/style.css
Project39-QRCodeGenerator/index.html
Project39-QRCodeGenerator/script.js
Project39-QRCodeGenerator/style.css
Project40-FlashiThings/index.html
Project40-FlashiThings/script.js
Project40-FlashiThings/style.css

Project40 Added

---

TypingSpeed/index.html
TypingSpeed/script.js
TypingSpeed/styles.css

This PR adds a Typing Speed Test game with live WPM calculation, real-time stats (time, words, WPM), and a responsive UI. Features include a sample text, a typing area, and a start/reset functionality.

Add Typing Speed Test Game with Dynamic WPM Calculation

---

Project14 - Play quiz/index.html
Project14 - Play quiz/questions.js
Project14 - Play quiz/readme.md
Project14 - Play quiz/script.js
Project14 - Play quiz/style.css

welcome to this quiz.
Here you can play quiz on four different topics and you can choose how many questions you want.
There are four different categories - Programming, Mathematics, Geography and entertainment, each with 5 to 25 questions.
Hope you enjoy it.
(there is some problem with the programming category🥲)

Play the quiz

---

Project 47-Resume Studio/index.html
Project 47-Resume Studio/script.js
Project 47-Resume Studio/style.css

Added Resume Studio , Add SWOC lable and ADVANCE to this Issue , @SOMNATH0904 
Screenrecording :
https://github.com/user-attachments/assets/a7b33812-f6d3-497b-b015-21205de5b5c9

Add Resume Studio

---

Project47 - Insect-Catch-Game/index.html
Project47 - Insect-Catch-Game/script.js
Project47 - Insect-Catch-Game/style.css

closes: #168 
A fun and interactive browser-based game where players test their reflexes by catching randomly appearing insects on the screen. Players start by selecting their favorite insect (e.g., Fly, Mosquito, Spider, or Roach) and then proceed to the game screen, where insects spawn at random locations. The goal is to catch as many insects as possible, with the game becoming progressively more challenging as more insects appear over time.
**Features:**
Insect Selection: Choose from multiple insects, each represented by a unique image.
Random Spawns: Insects appear at random locations with random rotations, adding a dynamic challenge.
Score Tracking: Keep track of how many insects you’ve caught.
Timer: A built-in timer shows how long you’ve been playing.
Increasing Difficulty: …

Add Insect catchy game

---

Project47-Dictionary/index.html
Project47-Dictionary/index.js
Project47-Dictionary/style.css

Added dictionary app
Fixes #146 
Screenshot

add dictionary app

---

Project47-GitHub_Profile_Finder/index.html
Project47-GitHub_Profile_Finder/index.js
Project47-GitHub_Profile_Finder/style.css

Added GitHub Profile Finder 
Fixes #155 
Screenshot

added GitHub Profile Finder

---

Project47-RandomQuoteGenerator/index.html
Project47-RandomQuoteGenerator/index.js
Project47-RandomQuoteGenerator/style.css

Added random quote generator
Fixes #156 
Screenshot

Added random quote generator

---

Project26 - PingPongGame/script.js

Added a maximum limit for the ball speed to ensure gameplay remains smooth and manageable, preventing overly fast movements that could disrupt the experience.
Improved the responsiveness of paddles by adjusting the computer paddle's AI level. This creates a better difficulty balance, making the game more challenging and enjoyable.
Made the canvas dynamically resize based on the browser window. This ensures the game adapts seamlessly to different screen sizes, enhancing the overall user experience.
Included sound effects for key events such as paddle hits, wall bounces, and scoring. These audio cues make the gameplay more engaging and immersive.
Added a game-over condition where the game ends when a player reaches a predefined score. This provides a clear endpoint and adds excitement to …

Enhancements and Bug Fixes

---

Project22 - PasswordGenerator/src/App.jsx

Fixed the off-by-one error in password character selection.
Replaced defaultChecked with checked for checkbox inputs. 
Corrected range input handling by parsing the value to an integer. 
Enhanced input and button styling for better UX.
Added htmlFor to labels for accessibility.
As mentioned in the issue number #140

Improve Password Generator Logic

---

Project15 - DigitalClock/script.js

**Time Offset Calculation:** Refactored the code to use time offset calculations exclusively during timezone updates to avoid unnecessary drift. This ensures that the displayed time remains accurate without additional computations.
**Simplified Theme Toggle:** Optimized the theme toggle functionality by utilizing classList.toggle with a second argument. This approach made the code more concise and easier to understand.
**Instant Timezone Updates:** Ensured that any changes to the timezone are immediately reflected in the UI, providing a seamless experience for the user.
**Code Comments and Refactoring:** Added meaningful comments throughout the code to improve readability and maintainability. Removed redundant code and replaced it with clearer, more efficient logic for better clarity.

Fix Time Drift and Improve Theme/Timezone Toggle Functionality

---

Project31 - PlantWebsite/script.js

**- Error Checks:** Added checks to ensure DOM elements exist before manipulation to prevent runtime errors.
**- Refactored Patterns:** Simplified repetitive code for better readability and maintainability.
**- Fallback Values: I**ncluded fallback values in functions like parseInt to handle unexpected inputs.
**- Centralized Logic:** Grouped common styles and logic for consistency and easier updates.
**- Organized Comments:** Cleaned up and structured comments for improved code understanding.
As mentioned in the issue number #134

Code Improvements and Fixes for JavaScript Features

---

Project16 - TicTacToe/script.js

**- Error Handling:** Added checks to ensure essential elements like the board and modal are properly initialized.
**- Refactoring:** Consolidated repetitive logic into reusable functions for better maintainability.
**- Winner Logic:** Improved determineOverallWinner to handle edge cases like no games played.
**- Readability:** Added comments and refactored redundant code for cleaner structure.
**- UI Fixes:** Ensured consistent modal behavior and accurate scoreboard updates.

 Code Enhancement and Bug Fixes

---

Project05 - ManageDailyTasks/index.html
Project05 - ManageDailyTasks/todolist.css
Project05 - ManageDailyTasks/todolist.js

**- Visual Design:** Modernized buttons, inputs, and containers for a responsive look.
**- Layout Fixes:** Aligned elements and resolved inconsistencies.
**- Interactive Effects:** Added smooth hover effects and transitions.
**- Task Features:** Optimized task addition, removal, and striking out.
**- PDF Fixes:** Fixed bugs in saving, viewing, and deleting PDFs.
**- Responsiveness:** Tested across devices for a consistent experience.
I am also attaching a screenshot of the UI changes

mprove UI and Fix Functionalities in "ManageDailyTask" 

---

Project48-Text Saver Extension/Text_Saver_Ext-main/content.js
Project48-Text Saver Extension/Text_Saver_Ext-main/popup.html
Project48-Text Saver Extension/Text_Saver_Ext-main/popup.js
Project48-Text Saver Extension/background.js
Project48-Text Saver Extension/content.js

Adding initial files
popup.html
popup.js
content.js

Adding Text Saver Extension

---

Project09 - SimpleCalculator/script.js

Hi I did these below changes : 
- Replaced eval with a safer alternative, such as the Function constructor, after sanitizing the input to allow only valid mathematical characters.
- Implemented input sanitization to prevent unsafe or unexpected characters from being processed
as mentioned in the issue number #198

Replaced eval with a Safer Calculation Method

---

Project71 - Bubble game/index.html
Project71 - Bubble game/script.js
Project71 - Bubble game/styles.css

I have added the project accept my PR.

Commited bubble game

---

Project71-DigitalClock/index.html
Project71-DigitalClock/index.js
Project71-DigitalClock/style.css

Added digital clock project.
Fixes #182

added digital clock

---

Project73-PasswordStrengthIndicator/index.html
Project73-PasswordStrengthIndicator/index.js
Project73-PasswordStrengthIndicator/style.css

Added password strength indicator project.
Fixes #185 
Screenshot

added password strength indicator

---

Project 73 - NQueens Game/index.html
Project 73 - NQueens Game/script.js
Project 73 - NQueens Game/style.css

Hey @SOMNATH0904  , please review and merge this PR under SWOC. Let me know if any changes or improvements are needed. 👍
N-Queens game Added , Here is the Demo of Game : 
https://github.com/user-attachments/assets/da41c367-3ba1-469e-a181-a5377d957ef9

Project 73 N Queens game

---

Project73-DrawingApp/index.html
Project73-DrawingApp/index.js
Project73-DrawingApp/style.css

Added drawing app project.
Fixes #220 
Screenshot

added drawing app

---

Project73-AutoTextEffect/index.html
Project73-AutoTextEffect/script.js
Project73-AutoTextEffect/style.css

Added auto text effect project.
Fixes #221 
Screenshot

added auto text effect

---

Project 74 - Palindrome Generator/index.html
Project 74 - Palindrome Generator/script.js
Project 74 - Palindrome Generator/style.css

Hey @SOMNATH0904  ,
Could you Please review and let me know if any further updates are needed and merge this PR under SWOC. 😊
Screenrecording : 
https://github.com/user-attachments/assets/0951e0f3-a09a-4222-b8e4-c0c1b7ff3b99

Palindrome Generator Fixed

---

Project81 - SimonSaysGame/index.html
Project81 - SimonSaysGame/script.js
Project81 - SimonSaysGame/style.css

@SOMNATH0904
I've added Simon Says Game Project.
Please review my PR.
Issue: #233

Added SimonSaysGame

---

Project81 - Voting_Application_Backend/package-lock.json
Project81 - Voting_Application_Backend/server/.gitignore
Project81 - Voting_Application_Backend/server/VoteApp.drawio
Project81 - Voting_Application_Backend/server/db.js
Project81 - Voting_Application_Backend/server/jwt.js
Project81 - Voting_Application_Backend/server/models/candidate.js
Project81 - Voting_Application_Backend/server/models/user.js
Project81 - Voting_Application_Backend/server/package-lock.json
Project81 - Voting_Application_Backend/server/package.json
Project81 - Voting_Application_Backend/server/routes/candidateRoutes.js
Project81 - Voting_Application_Backend/server/routes/userRoutes.js
Project81 - Voting_Application_Backend/server/server.js

Closes #234 
The Voting Application is a secure platform for conducting elections. Users can sign up with their Aadhar Card Number, view candidates, and vote. Admins can manage candidates by adding, updating, or deleting them. Built with Node.js, Express.js, and MongoDB, it uses JWT for secure access and data integrity.
Backend: Node.js, Express.js
Database: MongoDB (with Mongoose)
Authentication: JWT (JSON Web Token)
Testing/Client: Postman (for API testing)
This Voting Application allows users to:
- View a list of candidates.
- Vote for a candidate (one-time voting per user).
- View vote counts.
Admins can:
- Add, update, and delete candidates.
- View all votes and candidates in real-time.
The application is built using Node.js, Express.js, and MongoDB, with JWT authentication ensuring …

Adding Voting Application Backend

---

Project81 - formify/index.html
Project81 - formify/script.js
Project81 - formify/style.css

I hope you like my project and contributions! Looking forward to more interactions and exciting opportunities in the future.

 added formify

---

Project81-RandomChoicePicker/index.html
Project81-RandomChoicePicker/index.js
Project81-RandomChoicePicker/style.css

Added random choice picker project.
Fixes #248 
Screenshot

Added random choice picker

---

Project81-RecipeFinder/index.html
Project81-RecipeFinder/index.js
Project81-RecipeFinder/style.css

Added recipe finder project.
Fixes #184 
Screenshot

recipe finder

---

Project  82-  Space Ship game/flappyBird_script.js
Project  82-  Space Ship game/flappyBird_style.css
Project  82-  Space Ship game/index.html
Project  82-  Space Ship game/stars.js

Fixed this issue @SOMNATH0904 Add SWOC level to this PR 
https://github.com/user-attachments/assets/5790abf3-3e8f-48b8-9595-50c45d7fcd31

Add Space Ship Game

---

Project81 - NotesApp/index.html
Project81 - NotesApp/script.js
Project81 - NotesApp/style.css

#257 added 
https://github.com/user-attachments/assets/b53f9dd3-bdb0-4172-b27a-5990d8ce0fce

notes app added

---

Project81 - NotesApp/index.html
Project81 - NotesApp/script.js
Project81 - NotesApp/style.css
Project82 - WikipediaClone/index.html
Project82 - WikipediaClone/script.js
Project82 - WikipediaClone/style.css

project 82 wikipedia clone added #255 solved 
https://github.com/user-attachments/assets/5d435ac3-0cde-4c3c-a7d7-584e826f2521
https://github.com/user-attachments/assets/de28c8df-c7f4-47c7-9bcb-cdaff2510ebf

Wikipedia Clone added 

---

.idea/.gitignore
.idea/DevSphere.iml
.idea/inspectionProfiles/Project_Default.xml
.idea/modules.xml
.idea/vcs.xml
Project81-TempratureConvertor/index.html
Project81-TempratureConvertor/script.js
Project81-TempratureConvertor/style.css

Hey  @SOMNATH0904
Here is a compact temperature converter I built. Currently, it consists of only 3 scales, but it can add any number of temperature scales as needed.
Review the program and pass on comments and feedback of any changes need .

Temperature converter 

---

Project93-Temp_Converter/index.html
Project93-Temp_Converter/index.js
Project93-Temp_Converter/style.css

Added temperature converter project.
Fixes #265 
Screenshot

added temperature converter

---

Project93-CurrencyConverter/index.html
Project93-CurrencyConverter/script.js
Project93-CurrencyConverter/style.css

Added currency converter project.
Fixes #266 
Screenshot

added currency converter

---

Project93-GitHubProfileViewer/index.html
Project93-GitHubProfileViewer/index.js
Project93-GitHubProfileViewer/style.css

Added GitHub profile viewer project.
Fixes #268 
Screenshot

added GitHub profile viewer

---

Project93-WordGuessGame/index.html
Project93-WordGuessGame/index.js
Project93-WordGuessGame/style.css

Added word guess game project.
Fixes #269 
Screenshot

added word guess game

---

Project93 - Fun-Facts/index.html
Project93 - Fun-Facts/script.js
Project93 - Fun-Facts/style.css

@SOMNATH0904, I add a project look  Add SWOC level to this PR

Add Fun-Facts website

---

Project93 - Foodie Recepie App/.gitignore
Project93 - Foodie Recepie App/README.md
Project93 - Foodie Recepie App/index.html
Project93 - Foodie Recepie App/package-lock.json
Project93 - Foodie Recepie App/package.json
Project93 - Foodie Recepie App/src/App.css
Project93 - Foodie Recepie App/src/App.jsx
Project93 - Foodie Recepie App/src/components/Container.jsx
Project93 - Foodie Recepie App/src/components/FoodItem.jsx
Project93 - Foodie Recepie App/src/components/FoodList.jsx
Project93 - Foodie Recepie App/src/components/Fooddetail.jsx
Project93 - Foodie Recepie App/src/components/Innerconatiner.jsx
Project93 - Foodie Recepie App/src/components/Itemlist.jsx
Project93 - Foodie Recepie App/src/components/Nav.jsx
Project93 - Foodie Recepie App/src/components/Search.jsx
Project93 - Foodie Recepie App/src/components/container.module.css
Project93 - Foodie Recepie App/src/components/fooddetail.module.css
Project93 - Foodie Recepie App/src/components/fooditem.module.css
Project93 - Foodie Recepie App/src/components/innercontainer.module.css
Project93 - Foodie Recepie App/src/components/nav.module.css
Project93 - Foodie Recepie App/src/components/search.module.css
Project93 - Foodie Recepie App/src/main.jsx
Project93 - Foodie Recepie App/vite.config.js

closes #236  
Foodie Recipes App is a delightful application designed to inspire your culinary adventures by fetching a wide range of recipes. Developed with React.js, this app offers a user-friendly experience, enabling users to search for recipes, explore detailed instructions, and discover new dishes.
Frontend: React.js
Styling: CSS, Bootstrap
State Management: React Hooks
API: [Edamam API](https://developer.edamam.com/), [Spoonacular API](https://spoonacular.com/food-api) (or any other recipe API)
Other Tools: Git for version control

Add Foodie Recipes App

---

Project93-AnalogueClock/index.html
Project93-AnalogueClock/index.js
Project93-AnalogueClock/style.css

Added analogue clock project.
Fixes #294 
Screenshot

added analogue clock

---

Project93-MathAddition/index.html
Project93-MathAddition/index.js
Project93-MathAddition/style.css

Added math addition app project.
Fixes #295 
Screenshot

added math addition app

---

Project93-NumberGuessingGame/index.html
Project93-NumberGuessingGame/index.js
Project93-NumberGuessingGame/style.css

Added number guessing game project.
Fixes #296 
Screenshot

added number guessing game

---

Project93 - GithubProfileFinder/index.html
Project93 - GithubProfileFinder/script.js
Project93 - GithubProfileFinder/style.css

#155 solved github profile finder project added 
https://github.com/user-attachments/assets/79f7e7b7-0335-45aa-8c8f-a8f534661917

github profile finder added

---

Project93 - GithubProfileFinder/index.html
Project93 - GithubProfileFinder/script.js
Project93 - GithubProfileFinder/style.css
Project94 - DrawingApp/index.html
Project94 - DrawingApp/script.js
Project94 - DrawingApp/style.css
Project95 - ThemeClock/index.html
Project95 - ThemeClock/script.js
Project95 - ThemeClock/styles.css

#281 added 
https://github.com/user-attachments/assets/a9eb7083-e93e-4059-9e81-341d98f1295a

Theme clock project added 

---

Project113 - 3d-boxes-background/index.html
Project113 - 3d-boxes-background/script.js
Project113 - 3d-boxes-background/style.css

closes #301 
This project creates an interactive 3D boxes background effect using **HTML, CSS, and JavaScript**. The effect consists of multiple boxes forming a larger image, which animates when clicked.
- Clicking the **Magic 🎩** button toggles the transformation.
- Uses **CSS transitions** and **JavaScript DOM manipulation** to create the effect.
- Responsive and visually appealing animation.
- **HTML**: Structure of the page.
- **CSS**: Styling and animations.
- **JavaScript**: Dynamic box creation and interactions.

Add 3D Boxes Magic Background

---

Project113 - animated-countdown/index.html
Project113 - animated-countdown/script.js
Project113 - animated-countdown/style.css

closes #302 
This project creates an engaging animated countdown using **HTML, CSS, and JavaScript**. The countdown starts from 3 and ends with a "GO" message, followed by a replay button to restart the animation.
- Animated countdown from 3 to 0.
- "GO" message displayed at the end.
- Replay button to restart the countdown.
- Smooth CSS animations for transitions.
- **HTML**: Structure of the page.
- **CSS**: Styling and animations.
- **JavaScript**: Handles countdown logic and DOM manipulation.
1. **JavaScript** cycles through the numbers, applying animation classes.
2. The numbers animate in and out using **CSS keyframes**.
3. When the countdown reaches 0, "GO" is displayed.
4. Clicking the replay button restarts the countdown.

Add Animated Countdown

---

Project113-GreetingMessage/index.html
Project113-GreetingMessage/index.js
Project113-GreetingMessage/style.css

Added greeting message project.
Fixes #316 
Screenshot

added greeting message

---

Project113-BackgroundColorSwitcher/index.html
Project113-BackgroundColorSwitcher/index.js
Project113-BackgroundColorSwitcher/style.css

Added background color switcher project.
Fixes #319 
Screenshot

added background color switcher

---

Project28 - MemoryMatchingGame/script.js

Compared data-color attributes instead of innerHTML.
Added click event listeners to each card.
Locked the board during checks to prevent rapid clicks.
as i mentioned in the issue number #325

Card Matching Logic & Event Handling

---

Project40 - FlashiThings/script.js

- Replaced inner HTML comparison with data-color attribute for accurate matching.
- Added click event listeners directly to each card during the creation process.
- Implemented a board lock mechanism during matching checks to prevent rapid clicks from interfering with the game logic. 
I did all the changes as mentioned in the issue number #346

Code Improvements for Flashcard App

---

Project113-NumberSystemConverter/index.html
Project113-NumberSystemConverter/index.js
Project113-NumberSystemConverter/style.css

Added number system converter project.
Fixes #355 
Screenshot

added number system converter

---

Project113-AgeCalculator/index.html
Project113-AgeCalculator/index.js
Project113-AgeCalculator/style.css

Added age calculator app project.
Fixes #354 
Screenshot

added age calculator

---

Project113 - MealFinder/index.html
Project113 - MealFinder/script.js
Project113 - MealFinder/style.css

#356 added 
https://github.com/user-attachments/assets/50b26ca7-02b1-4905-8232-727037123f6c

meal finder added

---

Project113 - MealFinder/index.html
Project113 - MealFinder/script.js
Project113 - MealFinder/style.css
Project114 - MovieSeatBooking/index.html
Project114 - MovieSeatBooking/script.js
Project114 - MovieSeatBooking/style.css

#357 solved 
https://github.com/user-attachments/assets/6241656c-68b8-472e-8e9d-68056555aa72

Movie Seat booking project added

---

Project113-Calendar/index.html
Project113-Calendar/index.js
Project113-Calendar/style.css

Added calendar app project.
Fixes #336 
Screenshot

added calendar app

---

Project113-ToDoList/index.html
Project113-ToDoList/index.js
Project113-ToDoList/style.css

Added to do list app project.
Fixes #334 
Screenshot

added to do list app

---

HeartTrailAnimation/index.html
HeartTrailAnimation/index.js
HeartTrailAnimation/style.css

Added heart trail animation project.
Fixes #376 
Screenshot

added heart trail animation

---

RealTimeCharacterCounter/index.html
RealTimeCharacterCounter/index.js
RealTimeCharacterCounter/style.css

Added real time character counter project.
Fixes #375 
Screenshot

added real time character counter

---

DiceRollSimulator/index.html
DiceRollSimulator/index.js
DiceRollSimulator/style.css

Added dice roll simulator project.
Fixes #373 
Screenshot

added dice roll simulator

---

Project122 - NeonGlowErrorPage/index.html
Project122 - NeonGlowErrorPage/style.css

Add Neon Glow Error Project

---

Project123 - CardStyledAccordion/index.html
Project123 - CardStyledAccordion/script.js
Project123 - CardStyledAccordion/styles.css

Add Card Styled Accordion Project

---

Project 122- Devsphere Contributors/contributor.css
Project 122- Devsphere Contributors/contributor.js
Project 122- Devsphere Contributors/index.html

Hey @SOMNATH0904 , Could You Please Review and Merge this PR Under SWOC . 
In this , I crested Contributors Page , Where all Contributors who contribute in DEVSPHERE Project listed There , along with there github Profile and with Certificate Button where contributor Download there certificate for contribution in DEVSPHERE PROJECT . 
Screenrecording : 
https://github.com/user-attachments/assets/3fa5737f-5fc0-416d-81ab-f5312f39a1a1

Generate Certificate for Contributors

---

Project 123-Zombiee Shooter Game/index.html
Project 123-Zombiee Shooter Game/script.js
Project 123-Zombiee Shooter Game/style.css

Hey @SOMNATH0904 , PLease Review This PR and Merge this Under SWOC . 
Added Zombiee Shooter Game , Fully Responsive and 3d Game and Smoot Playing . 
Screenrecording : 
https://github.com/user-attachments/assets/3bffd980-4983-48f4-9f04-dd42796b0a1b

Zombiee Shooter Game Added

---

Project03 - SnakeGame/snake.html

#237 Issue Fixed 
Hey @SOMNATH0904 , Could You Please review and Merge this PR under SWOC . 
Screenrecording : 
https://github.com/user-attachments/assets/14de67e2-bb0c-4474-bc18-a25843bdbd03

Snake Game Fixed

---

memory game/index.html
memory game/script.js
memory game/style.css

This PR adds a new memory game file built with HTML, CSS, and JavaScript. The game is a simple, interactive memory challenge designed to demonstrate basic front-end development skills. It has been tested on Chrome and Firefox and works as expected. This contribution aims to enhance the repository with a fun and engaging project.

Added memory game file

---

memory game/index.html
memory game/script.js
memory game/style.css
personal finance dashboard/index.html
personal finance dashboard/script.js
personal finance dashboard/styles.css

This PR adds a Personal Finance Dashboard built with HTML, CSS, and JavaScript. The dashboard allows users to track income and expenses, view financial summaries, and interact with simple visual charts. Designed to be lightweight and responsive, it works seamlessly across devices. This project demonstrates basic front-end development skills and is ready for review.

personal finance dashboard

---

Project140 - Lyrics Search/index.html
Project140 - Lyrics Search/readme.md
Project140 - Lyrics Search/script.js
Project140 - Lyrics Search/style.css

feat: added powerful lyrics searcher

---

Project146 - Smart Form/form.css
Project146 - Smart Form/index.html

FIX #554 Smart Form

---

Vintage Paper Texture Background/index.html

Added Vintage Paper Texture Background

---

Soft Pastel Gradient with Floating Bubbles/index.html

added Soft Pastel Gradient with Floating bubbles Background

---

Project146 - Meme Generator/index.html
Project146 - Meme Generator/script.js
Project146 - Meme Generator/style.css

feat: added meme generator via imgflip api

---

Project146 - Memory Puzzle Game/index.html
Project146 - Memory Puzzle Game/script.js
Project146 - Memory Puzzle Game/style.css

feat: added memory puzzle game

---

Project146 - Crossword Puzzle Game/index.html
Project146 - Crossword Puzzle Game/script.js
Project146 - Crossword Puzzle Game/style.css

feat: added crossword puzzle game

---

Soft Blurry Glassmorphism Background/index.html

Adding Soft Glassmorphism blurry background

---

Aesthetic Starry Night with Shooting Stars/index.html

Add a Aesthetic Starry Night with Shooting Stars background

---

GardenNerds/.gitignore
GardenNerds/index.html
GardenNerds/readme.md
GardenNerds/styles.css

Added GardenNerds

---

Intenshala-Automation-Bot/.gitignore
Intenshala-Automation-Bot/LICENSE
Intenshala-Automation-Bot/README.md
Intenshala-Automation-Bot/internshala_bot/__init__.py
Intenshala-Automation-Bot/internshala_bot/__main__.py
Intenshala-Automation-Bot/internshala_bot/chat_gpt.py
Intenshala-Automation-Bot/internshala_bot/generate_report.py
Intenshala-Automation-Bot/internshala_bot/main.py
Intenshala-Automation-Bot/internshala_bot/resume_handler.py
Intenshala-Automation-Bot/setup.py

Added Internshala Automation Bot

---

Distance_converter/dist.css
Distance_converter/dist.html
Distance_converter/dist.js

Added Distance Converter

---

Butterfly_/Butterfly.html
Butterfly_/Butterfly.js

Added Butterfly

---

Virtual Debit Card/README.md
Virtual Debit Card/VCD.css
Virtual Debit Card/VCD.js
Virtual Debit Card/index.html

Added Virtual Debit Card

---

Project147 -Stock Market Analyser with Graphs/app.js
Project147 -Stock Market Analyser with Graphs/index.html
Project147 -Stock Market Analyser with Graphs/styles.css

feat: added stock market tracker

---

Project147 - Emoji Translator/index.html
Project147 - Emoji Translator/script.js
Project147 - Emoji Translator/styles.css

feat: added emoji translator

---

Project147 -Recipe Finder/index.html
Project147 -Recipe Finder/script.js
Project147 -Recipe Finder/styles.css

feat: added recipe finder via food api

---

Project147 - Nasa API for Astronomy data/index.html
Project147 - Nasa API for Astronomy data/style.css

feat: added nasa api for astronomy

---

Project148 - Code Splitting Demo/index.html
Project148 - Code Splitting Demo/script.js
Project148 - Code Splitting Demo/styles.css

feat: added code splitting demo

---

MovieSeatBooking/index.html
MovieSeatBooking/index.js
MovieSeatBooking/style.css

Added movie seat booking project.
Fixes #642 
Screenshot

added movie seat booking project

---

GroceryList/index.html
GroceryList/index.js
GroceryList/style.css

Added grocery list project.
Fixes #635 
Screenshot

added grocery list project

---

Facebook_UI/index.html
Facebook_UI/style.css

Added facebook UI project.
Fixes #638 
Screenshot

added facebook ui project

---

RGB_COLOR_GAME/index.html
RGB_COLOR_GAME/index.js
RGB_COLOR_GAME/style.css

Added rgb game project.
Fixes #640 
Screenshot

added rgb game project

---

Project148 - Markdown Editor/index.html
Project148 - Markdown Editor/script.js
Project148 - Markdown Editor/styles.css

feat: added a markdown editor

---

Project148 - Voice Assistant Demo/index.html
Project148 - Voice Assistant Demo/script.js
Project148 - Voice Assistant Demo/styles.css

Feat: added a voice assistant demo

---

Project148 - Population Density Map/app.js
Project148 - Population Density Map/index.html
Project148 - Population Density Map/styles.css

Feat: added population density map

---

Project148 - Debounce and Throttle Demo/index.html
Project148 - Debounce and Throttle Demo/readme.md
Project148 - Debounce and Throttle Demo/script.js
Project148 - Debounce and Throttle Demo/styles.css

feat: added debouncing and throttling demo

---

Project148 - Memory Leak Detection/index.html
Project148 - Memory Leak Detection/script.js
Project148 - Memory Leak Detection/styles.css

feat: added memory leak detector

---

Project148 -Network Performance Analyser/index.html
Project148 -Network Performance Analyser/script.js
Project148 -Network Performance Analyser/styles.css

feat: added network performance analyser

---

Project148 - Complex Caching Demo/index.html
Project148 - Complex Caching Demo/script.js
Project148 - Complex Caching Demo/styles.css

feat: added complex caching mechanism

---

Project148 - Code Profiler and Optimiser/index.html
Project148 - Code Profiler and Optimiser/readme.md
Project148 - Code Profiler and Optimiser/script.js
Project148 - Code Profiler and Optimiser/styles.css

feat: added code profiler and optimiser

---

Project148 - Speech Recognition Interface/index.html
Project148 - Speech Recognition Interface/script.js
Project148 - Speech Recognition Interface/styles.css

feat: added speech recognition interface

---

Project148 - Color Blindness Simulator/app.js
Project148 - Color Blindness Simulator/index.html
Project148 - Color Blindness Simulator/styles.css

feat: added color blindness simulator

---

Sign_In_Up_page/index.html
Sign_In_Up_page/index.js
Sign_In_Up_page/style.css

Added sign in and sign up project.
Fixes #696 
Screenshot

added sign in and sign up project

---

Project148 - Countdown Timer/index.html
Project148 - Countdown Timer/script.js
Project148 - Countdown Timer/style.css

feat: added a countdown timer

---

Project148 -Screen Reader Compatibility/app.js
Project148 -Screen Reader Compatibility/index.html
Project148 -Screen Reader Compatibility/readme.md
Project148 -Screen Reader Compatibility/styles.css

feat: added screen reader compatibility

---

Project148 -Battleship Game/index.html
Project148 -Battleship Game/script.js
Project148 -Battleship Game/style.css

feat: added battleship game

---

Project148 -Units convertor/index.html
Project148 -Units convertor/script.js
Project148 -Units convertor/styles.css

feat: added units convertor

---

Project148 - Password Generator/index.html
Project148 - Password Generator/script.js
Project148 - Password Generator/styles.css

feat: added a password generator

---

Project148 - Ecommerce Website/index.html
Project148 - Ecommerce Website/script.js
Project148 - Ecommerce Website/styles.css

feat: added ecommerce website

---

Project148 - Social Media Dashboard/index.html
Project148 - Social Media Dashboard/script.js
Project148 - Social Media Dashboard/styles.css

Feat: added social media dashboard

---

Project148 - Car Rental Website/index.html
Project148 - Car Rental Website/script.js
Project148 - Car Rental Website/styles.css

feat: added car rental website

---

Whatsapp_bot/README.md
Whatsapp_bot/SpamBot_script.txt
Whatsapp_bot/Spambot.py

Added Whatsapp bot

---

AI-Based-Sentiment-Analyzer/AI-Based_Sentiment_Analyzer.py
AI-Based-Sentiment-Analyzer/README.md

Added AI bases Sentiment Analyzer

---

Real-Time-Emotion-Detection-System/README.md
Real-Time-Emotion-Detection-System/main.py

Added Real time emotion detection system

---

Driver-Drowsiness-Detection-System/README.md
Driver-Drowsiness-Detection-System/main.py

Added Driver Drowsiness Detection System

---

CLI-Todo/CLIBasedTodo.js
CLI-Todo/CLIToDo.json
CLI-Todo/LICENSE
CLI-Todo/README.md
CLI-Todo/package-lock.json
CLI-Todo/package.json

Added CLI todo

---

WeatherCollector/LICENSE
WeatherCollector/README.md
WeatherCollector/console.py
WeatherCollector/csvtable.py
WeatherCollector/geocoding.py
WeatherCollector/main.py
WeatherCollector/record.py
WeatherCollector/requirements.txt
WeatherCollector/station.py

Added Weather Collector

---

AI Room Booking Chatbot [IBM WATSON]/IBM_Cloud_Function.py
AI Room Booking Chatbot [IBM WATSON]/README.md
AI Room Booking Chatbot [IBM WATSON]/skill-Room-Booking.json

Added AI Room Booking Chatbot

---

Smile Selfie Capture Project  [OPEN CV]/dataset/haarcascade_frontalface_default.xml
Smile Selfie Capture Project  [OPEN CV]/dataset/haarcascade_smile.xml
Smile Selfie Capture Project  [OPEN CV]/main.py

Added Smile Selflie Capture

---

IPL Score Prediction/First Innings Score Prediction - IPL.ipynb

Added IPL Score Prediction
